### ISSUE TITLE
Error creating pseudotranscriptome from RefSeq fasta/GTF

### ISSUE THREAD

**Issue by isaacvock** [erhard-lab/grandRescue#3]
Hello,

When running `gedi -e CreatePseudo ...` with a fasta and GTF file from RefSeq, it finishes in less than a second and no files are created. The output from gedi is:

```
2024-11-29 18:04:03.248 INFO OS: Linux 4.18.0-477.74.1.el8_8.x86_64 amd64
2024-11-29 18:04:03.301 INFO Java: OpenJDK 64-Bit Server VM 21.0.2-internal-adhoc.conda.src
2024-11-29 18:04:03.353 INFO Discovering classes in classpath
2024-11-29 18:04:03.573 INFO Preparing simple class references
2024-11-29 18:04:03.646 INFO Gedi version 1.0.6b (JAR) startup
2024-11-29 18:04:03.647 INFO Command: gedi -e CreatePseudo -fasta hg38.fa -gtf hg38.ncbiRefSeq.gtf -out pseudo
hg38.fa
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.base/java.util.regex.Matcher.checkMatch(Matcher.java:1852)
        at java.base/java.util.regex.Matcher.group(Matcher.java:687)
        at gedi.util.createOnlyExonGenome.fastaSeparator(createOnlyExonGenome.java:55)
        at executables.CreatePseudo.main(CreatePseudo.java:48)
2024-11-29 18:04:03.697 INFO Finished: gedi -e CreatePseudo -fasta hg38.fa -gtf hg38.ncbiRefSeq.gtf -out pseudo
2024-11-29 18:04:03.698 INFO Warnings: 0, errors: 0!
2024-11-29 18:04:03.699 INFO Took 462ms
```

I confirmed that this step works with a fasta and gtf from ensembl. Notably, the only real difference that I can think of is that the ensembl reference doesn't include the prefix "chr" in its chromosome names. Let me know if any additional information would be useful.

Best,
Isaac

**Comment by isaacvock** [comment]
Problem seems to be that the regex defined on line 54 of fastaSeparator method (`Pattern p = Pattern.compile("(\\S+)\\s");`) expects white space following the chromosome name in the fasta file. RefSeq fasta files typically looks like:

```
>chr1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

while a fasta file from ensembl might look like

```
>22 dna:chromosome chromosome:GRCh38:22:1:50818468:1 REF
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

The regex explicitly requires there to be whitespace following the chromosome name, which exists in the Ensembl but not the RefSeq fasta file. 

Maybe `Pattern p = Pattern.compile("^(\\S+)");` would be better, since the grandRescue function in question doesn't do anything with the rest of the ensembl seqname string anyway?

**Comment by ezecalvo** [comment]
Hi @isaacvock , I was wondering if this worked out for you. I took the easy route by re-formatting my ensemble fasta headers . I get no errors but also empty outputs.

edit: silly mistake from my part to keep the gtf gzipped, it's working now after the re-formatting.

**Comment by isaacvock** [comment]
That's good to know you were able to get the hack working, I haven't tried forking the repo and making the fix, just opted to not use grandRescue for now.
